version: '3.0'
services:
  php:
    build: ./docker/php
    environment:
#                               wsl hostname -I
      XDEBUG_CONFIG: 'client_host=192.168.72.201'
      XDEBUG_SESSION: 'PHPSTORM'
      PHP_IDE_CONFIG: 'serverName=drupal.local'
    volumes:
      - ./drupal:/var/www/html
    ports:
      - '80:80'
    networks:
      default:
        aliases: [ 'drupal.local' ]
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - mysql8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

volumes:
  mysql8:
