<?php

/**
 * @file
 * Provides enhancements for implementing and managing migrations.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\dicto_views\Constants;
use Drupal\node\Entity\Node;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_query_alter().
 */
function dicto_views_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'term' && $view->current_display === 'term_page') {
    foreach ($query->fields as $key => &$field) {
      if ($key === 'votingapi_result_node_field_data_1_value__coa') {
        $field['field'] = '(COALESCE(votingapi_result_node_field_data_1.value, 0) - COALESCE(votingapi_result_node_field_data.value, 0))';
      }
    }

    return;
  }

  if ($view->id() === 'glosar' && $view->current_display === 'page') {
    $argLen = strlen(current($view->args));
    if ($argLen > 0) {
      $query->where[0]['conditions'][0]['field'] = "SUBSTRING(node__field_slug.field_slug_value, 1, $argLen) = :node__field_slug_field_slug_value";
    }
  }

  if ($view->id() === 'glosar' && $view->current_display === 'block_second') {
    $path = Drupal::request()->getPathInfo();
    $parts = explode('glosar/', $path, 2);
    $arg = $parts[1] ?? '';
    if (strlen($arg > 0) || $arg === '0') {
      $glossary = substr($arg, 0, 1);
      $query->addWhere(0, 'SUBSTRING(node__field_slug.field_slug_value, 1, 1) = :node__field_slug_field_slug_value', [':node__field_slug_field_slug_value' => $glossary], 'formula');
    }
  }
}

/**
 * Implements hook_views_pre_execute().
 */
function dicto_views_views_pre_execute(ViewExecutable $view) {
  if ($view->id() === 'glosar' && $view->current_display === 'page' || $view->current_display === 'page_global') {
    /* @var $query \Drupal\Core\Database\Query\Select */
    $query = $view->build_info['query'];
    $query->groupBy('node__field_slug_field_slug_value');
    $query->addExpression('any_value(node_field_data.nid)', 'nid');
    unset($query->getFields()['nid']);

    $query = $view->build_info['count_query'];
    $query->groupBy('node__field_slug_field_slug_value');
    $query->addExpression('any_value(node_field_data.nid)', 'nid');
    unset($query->getFields()['nid']);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function dicto_views_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'views_query_alter':
    case 'entity_type_build':
      $group = $implementations['dicto_views'];
      unset($implementations['dicto_views']);
      $implementations['dicto_views'] = $group;
      break;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function dicto_views_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'term' && $view->current_display === 'term_page') {
    if (!isset($view->result[0])) {
      if (isset($view->args[0])) {
        $view->setTitle(str_replace('-', ' ', $view->args[0]));
      }
      return;
    }
    $title = $view->result[0]->_entity?->label();
    if ($title) {
      $view->setTitle($title);
    }
  }

  if ($view->id() === 'user_definitions') {
    $view->setTitle('$title');
    $user = \Drupal\user\Entity\User::load($view->args[0]);
    if ($user) {
      $view->setTitle($user->label() . ' - Definiții');
    }
  }
}

/**
 * A theme preprocess function to automatically allow view-based node
 * templates if called from a view.
 *
 * The 'modules/node.views.inc' file is a better place for this, but
 * we haven't got a chance to load that file before Drupal builds the
 * node portion of the theme registry.
 */
function dicto_views_preprocess_node(&$variables) {
  $a = 1;
}

/**
 * Implements hook_entity_presave().
 */
function dicto_views_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if (!isset($entity->field_slug)) {
    return;
  }

  $slugify = new \Cocur\Slugify\Slugify(['regexp' => Constants::SLUG_REGEX]);
  $entity->field_slug->value = $slugify->slugify($entity->label());

  $roles = Drupal::currentUser()->getRoles();
  if (!in_array('trusted', $roles)) {
    $entity->setUnpublished();
  } else {
    $entity->setPublished();
  }
}

/**
 * Implements hook_update_N().
 */
function dicto_views_update_9101(&$sandbox) {
  $slugify = new \Cocur\Slugify\Slugify(['regexp' => Constants::SLUG_REGEX]);
  $nodeIdList = \Drupal::entityQuery('node')->execute();
  $nodes = Node::loadMultiple($nodeIdList);
  foreach ($nodes as $node) {
    if (isset($node->field_slug)) {
      $node->field_slug->value = $slugify->slugify($node->label());
      $node->save();
    }
  }
}

/**
 * Implements hook_ajax_render_alter().
 */
function dicto_views_ajax_render_alter(array &$data) {
//  if (\Drupal::request()->query->has('__amp_source_origin')) {
//    $values = array_pop($data);
//    $new = array_pop($data);
//    $data = [];
//    $string = $values['data']->__toString();
//    if (preg_match('/reaction-count\">(.*?)<\/div>/', $string, $match) == 1) {
//      $up = $match[1];
//    }
//    if (preg_match("/\['down'\]\" class=\"votingapi-reaction-count\">(.*?)<\/div>/", $string, $match) == 1) {
//      $down = $match[1];
//    }
//    $data['new'] = $new['new'];
//    $data['up'] = $up;
//    $data['down'] = $down;
//  }
}

/**
 * Implements hook_entity_type_build().
 */
function dicto_views_entity_type_build(array &$entity_types) {
  if (isset($entity_types['vote'])) {
    $entity_types['vote']->setFormClass('votingapi_reaction', 'Drupal\dicto_views\Form\DictoVotingApiReactionForm');
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the search_block_form form.
 *
 * Since the exposed form is a GET form, we don't want it to send the form
 * tokens. However, you cannot make this happen in the form builder function
 * itself, because the tokens are added to the form after the builder function
 * is called. So, we have to do it in a form_alter.
 *
 * @see \Drupal\search\Form\SearchBlockForm
 */
function dicto_views_form_dicto_views_search_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_simple_sitemap_links_alter().
 */
function dicto_views_simple_sitemap_links_alter(array &$links, $sitemap_variant) {
  $a = 1;
}

/**
 * Implements hook_simple_sitemap_arbitrary_links_alter().
 */
function dicto_views_simple_sitemap_arbitrary_links_alter(array &$arbitrary_links, $sitemap_variant) {
  /* @var \Drupal\Core\Database\Connection $connection */
  $connection = Drupal::getContainer()->get('database');
  $query = $connection->query("
        select s.field_slug_value as value, max(n.created) as created
        from node__field_slug s
                 inner join node_field_data n on s.entity_id = n.nid
                 left join node__field_definitie nfd on s.entity_id = nfd.entity_id
        where nfd.entity_id is not null
        group by s.field_slug_value
  ");
  $nodes = $query->fetchAll();

  foreach ($nodes as $node) {
    $slug = $node->value;
    if ($slug === '') {
      continue;
    }
    $url = \Drupal\Core\Url::fromRoute('view.term.term_page', ['arg_0' => $slug], [
      'absolute' => TRUE,
      'https' => TRUE,
      'base_url' => 'https://dictionar-urban.ro',
    ]);
    $uri = $url->toString();
    $arbitrary_links[] = [
      'lastmod' => date('c', $node->created),
      'priority' => '1.0',
      'changefreq' => 'monthly',
      'images' => [],
      'meta' => [
        'path' => $url->getInternalPath(),
      ],
      'langcode' => 'ro',
      'url' => $uri,
      'alternate_urls' => [
        'ro' => $uri,
      ]
    ];
  }
}

function dicto_views_form_user_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['account'])) {
    unset($form['account']['mail']);
    unset($form['account']['pass']);
    unset($form['account']['current_pass']);
  }
  if (isset($form['actions']['delete'])) {
    unset($form['actions']['delete']);
  }
}
